#!/bin/bash

## First we make the working directory
sudo mkdir -p /tmp/pluginstall &> /dev/null

#choose version of ubuntu
#Input code browser
function strinput {
 unset refstr
 echo -n "$1"
 read refstr
}

## Ask if they agree to file bug reports, sort of a reminder
echo
echo "This script is used to setup 64-bit Adobe Flash 10 Square."
echo ""
echo "By downloading the software listed below, I acknowledge that I have read and agreed to the terms of the Flash Player 'Square' License, the Adobe.com Terms of Use and the Adobe Online Privacy Policy."
echo "See http://labs.adobe.com/technologies/eula/flashplayer10.html"
echo ""
echo " Do you agree? yes or no : "


if [ "$installtype" = "" ]
then
 echo -n "(please type the whole word in lower case letters)"
 strinput
else
 refstr=$installtype
fi

if [ "$refstr" = "yes" ]
then
 echo "Flash installing."


## First we uninstall and remove all the existing flash packages

# No longer trying to reply nspluginwrapper since Acrobat Reader 9 requires it
#sudo apt-get -y purge nspluginwrapper
sudo apt-get -y purge mozilla-plugin-gnash
sudo apt-get -y purge swfdec-mozilla
sudo apt-get -y purge flashplugin-nonfree
#sudo rm -rfd /usr/lib/nspluginwrapper
sudo rm -f /usr/lib/firefox-addons/plugins/libflashplayer.so
sudo rm -f /usr/lib/mozilla/plugins/libflashplayer.so
sudo rm -f /usr/lib/mozilla/plugins/flashplugin-alternative.so
sudo rm -f /usr/lib/mozilla/plugins/npwrapper*flash*so
rm -f ~/.mozilla/plugins/*flash*so

## What is current version?
export version="2_p3_64bit_linux_111710"
## Then we make a temp folder and download the new plugin
cd /tmp/pluginstall
sudo wget http://download.macromedia.com/pub/labs/flashplayer10/flashplayer10_$version.tar.gz

## Next we extract and place the plugin
sudo tar xvf flashplayer10_$version.tar.gz
sudo mv libflashplayer.so /usr/lib/mozilla/plugins/
sudo ln -s /usr/lib/mozilla/plugins/libflashplayer.so /usr/lib/firefox-addons/plugins/

echo "Please restart Firefox to enable Flash"

elif [ "$refstr" = "no" ]
then
 echo "I am sorry but you have to agree. "

else
 echo  " I am sorry but you have to agree. "
 echo
fi

