#!/bin/bash

if [ $( uname ) == "Darwin" ]; then
    target="/Volumes/KEYS"
else
    target="/media/KEYS"
fi

if ! [ -d "$target" ]; then
    echo "target $target does not exist"
    echo "Is the drive plugged in?"
    exit 1
fi

sudo cp -R "$HOME/.ssh" "$target/"
sudo cp "$HOME/local/toehold" "$target/"
sudo cp "$HOME/.gitconfig" "$target/"
sudo cp "$HOME/.gitignore_master" "$target/"
sudo ls -al "$target"
sudo tree -a "$target/.ssh"
