#!/bin/bash
THISDIR="$(cd `dirname "$0"` && pwd)"
ROOTDIR="$( dirname "$THISDIR" )"
LIBDIR="$ROOTDIR/lib"
CONFDIR="$ROOTDIR/conf"

source "$CONFDIR/conf.sh"
source "$LIBDIR/utils.sh"

main () {
    local src="$HOME"
    local dest="/archive/snapbak/kixx"
    local logfile="$LOGDIR/snapbak.log"
    local excludefile="$CONFDIR/snapbak_exclude.list"

    ensure_dir $LOGDIR
    ensure_dir $dest

    rsync \
        --recursive \
        --links \
        --perms \
        --times \
        --owner \
        --progress \
        --human-readable \
        --log-file="$logfile" \
        --exclude-from="$excludefile" \
        "$src/" "$dest/" || fail "$0: rsync failed"
}

main "$@"
