#!/bin/bash
# Usage: k snapbak
# Summary: Sync my entire home directory with the archive directory.
# Help: Uses rsync to copy the delta of the two directories.

source "$_K_LIB/utils.sh"

main () {
    local src="$HOME"
    local dest="/archive/snapbak/kixx"
    local excludefile="$_K_CONF/snapbak_exclude.list"

    ensure_dir $dest

    rsync \
        --recursive \
        --links \
        --perms \
        --times \
        --owner \
        --progress \
        --human-readable \
        --exclude-from="$excludefile" \
        "$src/" "$dest/" || fail "$0: rsync failed"
}

main "$@"
