#!/bin/bash
# Usage: k sync <command> [--write]
# Summary: Sync files and folders between machines.
# Help: Used primarily as another "Dropbox".
#
# COMMANDS
#   push        Push files to the remote location.
#   pull        Pull files from the remote location.
#   push-delete Push files to the remote location, deleting those that do not
#               exist locally.
#   pull-delete Pull files from the remote location, deleting those that did not
#               exit remotely.
#
# OPTIONS
#   --write     If this flag is not set, only a dry run will happen, without
#               actually writing anything to disk.

# Pull in the configs
source "$_K_CONF/conf.sh"

rsync_opts="\
--recursive \
--compress \
--links \
--perms \
--times \
--omit-dir-times \
--owner \
--group \
--progress \
--human-readable \
"

main () {
    local cmd="$1"
    local write="$2"
    local remote="$REMOTE" # sourced from conf.sh file.

    local opts="$rsync_opts --exclude-from=$_K_CONF/sync_exclude.list"
    if [ "$write" != "--write" ]; then
        opts="--dry-run $opts"
    fi
    if [ "$cmd" == "push" ] || [ "$cmd" == "push-delete" ]; then
        opts="--partial $opts"
    fi

    case $cmd in
        'push')
            sync "$opts" "$HOME" "$remote"
            ;;
        'pull')
            sync "$opts" "$remote" "$HOME"
            ;;
        'push-delete')
            sync "--delete $opts" "$HOME" "$remote"
            ;;
        'pull-delete')
            sync "--delete $opts" "$remote" "$HOME"
            ;;
        * )
            echo "COMMANDS"
            echo "  push        Push files to the remote location."
            echo "  pull        Pull files from the remote location."
            echo "  push-delete Push files to the remote location, deleting those that do not"
            echo "              exist locally."
            echo "  pull-delete Pull files from the remote location, deleting those that did not"
            echo "              exit remotely."
            ;;
    esac
}

sync () {
    local opts="$1"
    local src="$2"
    local dest="$3"
    rsync $opts "$src/" "$dest/"
}

main $@
