#!/usr/bin/env python
# Usage: ksys setupmac
# Summary: Setup a fresh OS X install.
# Help: Sets up my personal work environment for Mac OS X in an idempotent way.

from os import path, environ
import subprocess

from lib import pyutil

_KSYS_ROOT = environ['_KSYS_ROOT']


def main():
    # Install dotfiles
    ksys = path.join(_KSYS_ROOT, 'bin', 'ksys')
    msg = "There was a problem installing the 'dotfiles'."
    pyutil.sub_or_exit("%s install dotfiles" % ksys, msg)

    # Install Homebrew.
    install_homebrew()

    # Install the Homebrew version of Git.
    install_git()

    print "Done."
    print "You'll probably want to restart your shell."
    return


def install_homebrew():
    if path.exists('/usr/local/bin/brew'):
        print "Homebrew already installed."
        homebrew_doctor()
        return

    # Install Homebrew.
    installer = path.join(_KSYS_ROOT, 'scripts', 'install-homebrew.rb')
    msg = """There was a problem in the homebrew install script: '%s'.
        """ % installer
    pyutil.sub_or_exit("ruby %s" % installer, msg)
    homebrew_doctor()

    print "Homebrew installed."
    return


def homebrew_doctor():
    # Run the doctor.
    msg = "There is a problem with the homebrew installation."
    pyutil.sub_or_exit("brew doctor", msg)
    return


def install_git():
    if path.exists('/usr/local/bin/git'):
        print "Git already installed via Homebrew."
        return

    # Install git with bash-completion
    msg = "There was a problem installing git with homebrew."
    pyutil.sub_or_exit('brew install git bash-completion', msg)

    print "Homebrew installed git."


if __name__ == '__main__':
    main()
