#!/bin/bash
# Usage: ksys backup-etc <target_dir>
# Summary: Copy and archive (tar) the root /etc directory to another location (not for OSX).
# Help: Useful just before wiping out an existing OS, or making system level changes.
#
#   <target_dir> - The destination directory for the archive.

source "$_KSYS_LIB/utils.sh"

main () {
    local name="$( hostname -f )"
    local target="$HOME/Downloads"

    if [ ! -z $1 ]; then
        target=${1%/}
    fi

    if [ ! -d "$target" ]; then
        echo "$target is not a directory."
        exit 1
    fi

    local full_name="$target/etc-$name-$DATE_TODAY$uname.tar.bz2"

    echo 'backing /etc dir up to '$full_name
    sudo tar -cjf $full_name /etc || fail "Unable to tar archive"

    echo 'done OK'
}

main "$@"
