#!/usr/bin/env python
# Usage: ksys setupmac
# Summary: Setup a fresh OS X install.
# Help: Sets up my personal work environment for Mac OS X in an idempotent way.

from os import path, environ
import subprocess

from lib import pyutil

_KSYS_ROOT = environ['_KSYS_ROOT']

def main():
    install_homebrew()
    install_git()
    if subprocess.call([path.join(_KSYS_ROOT, 'bin', 'ksys'), 'install', 'dotfiles']) is not 0:
        pyutil.exit("""\
                There was a problem installing the 'dotfiles'.
                """)

    print "Done."
    print "You'll probably want to restart your shell."


def install_homebrew():
    if path.exists('/usr/local/bin/brew'):
        print "Homebrew already installed."
        return

    install_homebrew = path.join(_KSYS_ROOT, 'scripts', 'install-homebrew.rb')

    if subprocess.call(['ruby', install_homebrew]) is not 0:
        pyutil.exit("""\
                There was a problem in the homebrew install script: '%s'.
                """ % install_homebrew)

    if subprocess.call(['brew', 'doctor']) is not 0:
        pyutil.exit("""\
                There is a problem with the homebrew installation.
                """)
    print "Homebrew installed."


def install_git():
    if path.exists('/usr/local/bin/git'):
        print "Git already installed via Homebrew."

    if subprocess.call(['brew', 'install', 'git', 'bash-completion']) is not 0:
        pyutil.exit("""\
                There was a problem installing git with homebrew.
                """)

    print "Homebrew installed git."


if __name__ == '__main__':
    main()
